### ISSUE TITLE
Restrict coefficients in gaussian state space models

### ISSUE THREAD

**Issue by sivakon** [helske/KFAS#13] opened 2016-05-30 10:38 UTC
Can we specify or impose restrictions on regression coefficients in state space models? May be, put additional constraints on the optimization algorithm in fitSSM?

**Comment by helske** [comment] 2016-05-31 07:35
Do you mean bound constraints like beta_1 > 0? Instead of estimating the coefficients via Kalman filter, you could set them as fixed with `a1[i] = coef[i]` and` P1[i,i] = P1inf[i,i] = 0` in `updatefn `of `fitSSM`. But problem with this is that now you are pretending that you know the coefficients and the resulting model underestimates the uncertainties of your forecasts etc.  Another solution would be to add hard penalization to the log-likelihood, for example by adding `checkfn `function to `fitSSM`, which runs Kalman filter and returns `FALSE `if the estimated coefficients are out of bounds. Note that for computational performance it would be better to not use `fitSSM `here, but use optim and your own objective function directly, where the objective function runs the `KFS `with` smoothing = "none"`, and returns loglik if contraints are satisfied and Inf otherwise (or -Inf if maximizing). This way you only run Kalman filter once instead of twice.

**Comment by sivakon** [comment] 2016-06-02 12:42
Can you give me an example on how to penalize likelihood in `checkfn`?

**Comment by helske** [comment] 2016-06-06 10:28
When writing an example, I realized that my initial idea of using `checkfn` isn't that good after all, at least not in general, because the least squares estimate of the regression coefficient by Kalman filter if often independent or at least almost independent of the variance parameters of the model. Simplest case is just an ordinary regression model.

The former approach should still work (with the caveats I mentioned previously).

**Closed** 2020-11-09 06:59 UTC
