### ISSUE TITLE
Function rstandard(kfs, "state") not working properly

### ISSUE THREAD

**Issue by matteopelagatti** [helske/KFAS#29] opened 2018-01-24 10:16 UTC
Most of the times, when I call the following functions to obtain the auxiliary residuals

```
kfs1 <- KFS(fit1$model, smoothing = c("signal", "disturbance", "state"))
res_eps <- rstandard(kfs1, "pearson")
res_eta <- rstandard(kfs1, "state")
```
I get the error

> Error in dimnames(data) <- list(NULL, names) : 
>   length of 'dimnames' [2] not equal to array extent

associated to the call `rstandard(kfs1, "state")` .

My workaround is the following, but I think this bug should be fixed.
```
res_eta1 <- kfs1$etahat[, 1] / sqrt(fit1$model$Q[1, 1, ] - kfs1$V_eta[1, 1, ])
res_eta2 <- kfs1$etahat[, 2] / sqrt(fit1$model$Q[2, 2, ] - kfs1$V_eta[2, 2, ])
```

**Comment by helske** [comment] 2018-01-24 11:08
Can you give a reproducible example? I just ran all my test cases without an error. Are you using the latest version of the package? There was that kind of error in KFAS while ago, but it was already fixed in version 1.2.10.

**Comment by matteopelagatti** [comment] 2018-01-25 13:51
Dear Jouni,
probably it is a version problem, since I see that the version of the
package installed in the labs of my university is 1.2.9. However, when I
ask RStudio for package updates, it says that I have the latest version.
I attach the R Markdown: source and compiled html.
Thanks for developing this great package.
Best regards
Matteo

2018-01-24 12:08 GMT+01:00 Jouni Helske <notifications@github.com>:

**Comment by matteopelagatti** [comment] 2018-01-25 13:59
Here are the links to the files mentioned in my previous comment:
[Rmd source](https://drive.google.com/open?id=1JdgUchIDF7yiMPt_46qwcA5hlqtuXK2w)
[complied HTML](https://drive.google.com/open?id=1pphda3XOjUm0xftqioOv_mPytG194afJ)

**Comment by helske** [comment] 2018-01-25 14:07
It works for me so it must be a version problem. I don't know why  Rstudio doesn't find the latest version, but you can install it "manually" as `install.packages("KFAS")`.

**Closed** 2019-09-14 16:50 UTC
