### ISSUE TITLE
Limiting the number of trig functions in SSMseasonal using multiple SSMcycle

### ISSUE THREAD

**Issue by andrewbcooper** [helske/KFAS#21] opened 2017-04-06 18:08 UTC
Thank you again for all you work on this!  I haven't seen this mentioned in any of the documentation, but am I correct that I can limit the number of trigonometric functions / harmonics in SSMseasonal by using multiple SSMcycles?  For example, SSMseasional(period=12, sea.type=c("trigonometric") produces 11 functions, (6 harmonics with sea_trig*6 = 0).  If I want only use the first 4 functions (2 harmonics), I could do something like SSMcycle(period=12) + SSMcycle(period=6).  Is this correct, or am I missing something? Thanks again!

**Comment by helske** [comment] 2017-04-07 08:15
Hmm, I have never though of obtaining the harmonics like that. But I got two similar questions few months ago, where the goal  was to use only subset of the harmonics, and I suggested this:

> There isn't such functionality available in KFAS, but you can of course get such model "manually". I guess the easiest way to achieve that is to first build the seasonal component with all harmonics using SSMseasonal, and then adjust the output matrices Z, T etc by selecting only the rows/columns corresponding to the harmonics you want, and then you can input those into the model using SSMcustom function. So something like this:

```
sea <- SSMseasonal(period = 12, Q = 1, sea.type = "trigonometric")
harmonics <- c(1, 3)
ind <- rep(harmonics, each = 2) * rep(1:2, each = 2) + 0:1

names(sea)
Z <- sea$Z[, ind, drop = FALSE]
T <- sea$T[ind, ind]
R <- sea$R[ind, ind]
Q <- sea$Q[ind, ind, 1]
P1 <- sea$P1[ind, ind]
P1inf <- sea$P1inf[ind, ind]
a1 <- sea$a1[ind]
snames <- sea$state_names[ind]
model <- SSModel(rnorm(100) ~ SSMcustom(Z = Z, T = T, R = R,
  Q = Q, P1 = P1, P1inf = P1inf, a1 = a1, state_names = snames))
```

At that time I asked the them to test the code and report back to me if it worked as intended, so the functionality could then later be added to the `SSMseasonal` function itself. But I never got replies...

**Comment by andrewbcooper** [comment] 2017-04-07 17:16
I made a few modifications just to I could understand what it was doing, but it looks like both approaches work very well!  Here's my exploration:

library(KFAS)

# Make sure the data is available, it's in the datasets library
nottem

# Fit a seasonal model to the Average Monthly Temperatures at Nottingham, 1920–1939
# Just to make sure it works
AllHarmonics <- SSModel(nottem ~ SSMseasonal(period=12,Q=1,sea.type="trigonometric"))
AllHarmonics.fit <- fitSSM(AllHarmonics, inits=c(rep(0,11)),method="L-BFGS-B",lower=c(rep(0,11)),upper=c(rep(100,11)))
AllHarmonics.out <- KFS(AllHarmonics.fit$model,nsim=10000)
AllHarmonics.predict <- predict(AllHarmonics.fit$model,interval="prediction",nsim=10000,level=.9)

# Plot the states over time
plot(coef(AllHarmonics.out)[,1:10])
plot(coef(AllHarmonics.out)[,11:12])

# Fit a seasonal model to the Average Monthly Temperatures at Nottingham, 1920–1939
# Using only the first 2 harmonics (NOTE: changed this from code you sent - I couldn't figure out the logic behind your ind)
# Also, in order to get the same behavior of the intercept, I needed to set Q=NA in the "sea" model.  Setting Q=1 allowed the 
# intercept to vary over time 

sea <- SSMseasonal(period = 12, Q = NA, sea.type = "trigonometric")
ind <- 1:4

#Extract only the components for the first 2 harmonics
names(sea)
Z <- sea$Z[1, ind, drop = FALSE]
myT <- sea$T[ind, ind]
myR <- sea$R[ind, ind]
Q <- sea$Q[ind, ind, 1]
P1 <- sea$P1[ind, ind]
P1inf <- sea$P1inf[ind, ind]
a1 <- sea$a1[ind,1]
snames <- sea$state_names[ind]


TwoHarmonicsSea <- SSModel(nottem ~ SSMcustom(Z = Z, T = myT, R = myR,
                                              Q = Q, P1 = P1, P1inf = P1inf, a1 = a1, state_names = snames))
TwoHarmonicsSea.fit <- fitSSM(TwoHarmonicsSea, inits=c(rep(0,4)),method="L-BFGS-B",lower=c(rep(0,4)),upper=c(rep(100,4)))
TwoHarmonicsSea.out <- KFS(TwoHarmonicsSea.fit$model,nsim=10000)
TwoHarmonicsSea.predict <- predict(TwoHarmonicsSea.fit$model,interval="prediction",nsim=10000,level=.9)

#Plot the states
plot(coef(TwoHarmonicsSea.out))

#Compare to the first 5 states when fitting the full Seasonal (As expected: pretty close, but not exact)
plot(coef(AllHarmonics.out)[,1:5])

plot(coef(TwoHarmonicsSea.out)[,2]~coef(AllHarmonics.out)[,2])
plot(coef(TwoHarmonicsSea.out)[,3]~coef(AllHarmonics.out)[,3])
plot(coef(TwoHarmonicsSea.out)[,4]~coef(AllHarmonics.out)[,4])
plot(coef(TwoHarmonicsSea.out)[,5]~coef(AllHarmonics.out)[,5])


cor(coef(TwoHarmonicsSea.out)[,2],coef(AllHarmonics.out)[,2])
cor(coef(TwoHarmonicsSea.out)[,3],coef(AllHarmonics.out)[,3])
cor(coef(TwoHarmonicsSea.out)[,4],coef(AllHarmonics.out)[,4])
cor(coef(TwoHarmonicsSea.out)[,5],coef(AllHarmonics.out)[,5])

# Compare predictions from the reduced seasonal model and full seasonal model
# As expected: very close

cor(AllHarmonics.predict[,"fit"],TwoHarmonicsSea.predict[,"fit"])
cor(AllHarmonics.predict[,"lwr"],TwoHarmonicsSea.predict[,"lwr"])
cor(AllHarmonics.predict[,"upr"],TwoHarmonicsSea.predict[,"upr"])


# Fit a seasonal model to the Average Monthly Temperatures at Nottingham, 1920–1939
# using SSMcycle with period 12/1 and 12/2 for the first 2 harmonics

TwoHarmonicsCycle <- SSModel(nottem ~ SSMcycle(period=12,Q= NA) + SSMcycle(period=6,Q=1))
TwoHarmonicsCycle.fit <- fitSSM(TwoHarmonicsCycle, inits=c(rep(0,4)),method="L-BFGS-B",lower=c(rep(0,4)),upper=c(rep(100,4)))
TwoHarmonicsCycle.out <- KFS(TwoHarmonicsCycle.fit$model,nsim=10000)
TwoHarmonicsCycle.predict <- predict(TwoHarmonicsCycle.fit$model,interval="prediction",nsim=10000,level=.9)

#Plot the states
plot(coef(TwoHarmonicsCycle.out))

# Compere the estimated States between the 2-cycle model and reduced Seasonal model
# Get the same answer.  Yay!

plot(coef(TwoHarmonicsSea.out))
plot(coef(TwoHarmonicsCycle.out)[,2]~coef(TwoHarmonicsSea.out)[,2])
plot(coef(TwoHarmonicsCycle.out)[,3]~coef(TwoHarmonicsSea.out)[,3])
plot(coef(TwoHarmonicsCycle.out)[,4]~coef(TwoHarmonicsSea.out)[,4])
plot(coef(TwoHarmonicsCycle.out)[,5]~coef(TwoHarmonicsSea.out)[,5])


cor(coef(TwoHarmonicsCycle.out)[,2],coef(TwoHarmonicsSea.out)[,2])
cor(coef(TwoHarmonicsCycle.out)[,3],coef(TwoHarmonicsSea.out)[,3])
cor(coef(TwoHarmonicsCycle.out)[,4],coef(TwoHarmonicsSea.out)[,4])
cor(coef(TwoHarmonicsCycle.out)[,5],coef(TwoHarmonicsSea.out)[,5])

# Compare prediction intervals between the 2-cycle model and reduced Seasonal model

cor(TwoHarmonicsCycle.predict[,"fit"],TwoHarmonicsSea.predict[,"fit"])
cor(TwoHarmonicsCycle.predict[,"lwr"],TwoHarmonicsSea.predict[,"lwr"])
cor(TwoHarmonicsCycle.predict[,"upr"],TwoHarmonicsSea.predict[,"upr"])

# Compare the 24-month ahead predictions between the 2-cycle model and reduced Seasonal model
TwoHarmonicsCycle.predict24 <- predict(TwoHarmonicsCycle.fit$model,interval="prediction",nsim=10000,level=.9,n.ahead = 24)
TwoHarmonicsSea.predict24 <- predict(TwoHarmonicsSea.fit$model,interval="prediction",nsim=10000,level=.9,n.ahead = 24)

cor(TwoHarmonicsCycle.predict24[,"fit"],TwoHarmonicsSea.predict24[,"fit"])
cor(TwoHarmonicsCycle.predict24[,"lwr"],TwoHarmonicsSea.predict24[,"lwr"])
cor(TwoHarmonicsCycle.predict24[,"upr"],TwoHarmonicsSea.predict24[,"upr"])

Thanks again for all your hard work on this!!

**Comment by helske** [comment] 2017-04-18 16:41
I just added this functionality to the package: There is now argument `harmonics` in `SSMseasonal` which is used to extract corresponding subharmonics of the seasonal component. Currently this only works for the univariate case although it would be pretty straightforward to generalize this.

I'll close this now, if you see any problems, feel free to re-open.

**Closed by helske** 2017-04-18 16:41 UTC
