### ISSUE TITLE
Problems with standardized residuals 

### ISSUE THREAD

**Issue by Vera1996** [helske/KFAS#52] opened 2020-09-17 12:56 UTC
Dear Jouni,

the output of the function rstandard() produces NA values for the first 19 standardized residuals. My script is attached. 
Is there a solution to this? Thanks a lot!

[Standardized residuals .R.zip](https://github.com/helske/KFAS/files/5239184/Standardized.residuals.R.zip)

**Comment by helske** [comment] 2020-09-18 07:05
Sorry, I cannot run your code as I don't have access to your variables.

But I'm pretty sure this is due to diffuse initialization which leads to NA values in the residuals until the diffuse phase has ended. (as the variance F is in some sense not really defined). You can switch to nondiffuse initialization (by defining P1 and setting P1inf to zero when building your model) if you need residuals for all time points and it otherwise makes sense to your model.

**Comment by Vera1996** [comment] 2020-09-30 14:20
Oke thanks for your answer! Where do I need to define the P1 and P1inf initialization in the code below? When I put the initialization into the SSM regression, my Kalman output coefficient is the same for every variable When I put the initialization into the SSMtrend I get an error. I hope you can help me. Thanks a lot!

model <- SSModel(covid_new[, 1:4] ~ SSMtrend(2, Q = list(matrix(NA, 4, 4), matrix(NA, 4, 4))) + 
                   SSMregression(list(~lag_9$Germany, 
                                      ~lag_9$Netherlands, 
                                      ~lag_9$Spain, 
                                      ~lag_9$Sweden)) , H = matrix(NA, 4, 4))

**Comment by helske** [comment] 2020-11-09 06:47
Sorry, missed this earlier. If you want to initialize the states corresponding to the `SSMtrend` component, you but P1 and/or P1inf inside `SSMtrend`, and similarly for `SSMregression`. You can check that the final `P1` and `P1inf` are like you wanted them to be by `model$P1` and `model$P1inf` (you can also modify them later by assigning to those components, but you need to be careful not to change the dimensions of the matrices)

**Closed** 2021-05-08 09:34 UTC
